criaCartao(
    'Programaçao',
    'O que e Python?',
    'O Python e uma linguagem de programaçao'
)

criaCartao(
    'Geografia',
    'Qual a capital da França?',
    'A capital da França e  Paris'
)

criaCartao(
    'Programaçao',
    'O que e uma funçao?',
    'Uma funçao e um bloco de codigo que executa uma tarefa'
)

criaCartao(
    'Lingua inglesa',
    'Como se diz oi em Ingles?',
    'Oi em Ingles e HI (RAI)'
)